# Generated by Django 5.2.8 on 2025-11-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_criado_em_produto_estoque_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
