# Generated by Django 5.2.8 on 2025-11-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produtoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='especificacoes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
