# Generated by Django 5.2.8 on 2025-11-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['-padrao', '-criado_em'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='is_padrao',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='receber_notificacoes_pedido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='receber_promocoes',
        ),
        migrations.AddField(
            model_name='endereco',
            name='nome_destinatario',
            field=models.CharField(default='Destinatário', max_length=150, verbose_name='Nome do destinatário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='padrao',
            field=models.BooleanField(default=False, verbose_name='Endereço principal'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referência'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='rua',
            field=models.CharField(default='Destinatário', max_length=150, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
    ]
