# Generated by Django 5.2.8 on 2025-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_endereco_options_rename_user_endereco_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome completo'),
        ),
    ]
