# Generated by Django 5.2.8 on 2025-12-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfil_telefone_perfil_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='apelido',
            field=models.CharField(blank=True, help_text='Ex: Casa, Trabalho, Depósito...', max_length=30, null=True, verbose_name='Apelido do endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência'),
        ),
    ]
