# Generated by Django 5.2.8 on 2025-12-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estimativa_entrega',
            field=models.DateField(blank=True, help_text='Data estimada de entrega do pedido.', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando_pagamento', 'Aguardando pagamento'), ('pagamento_aprovado', 'Pagamento aprovado'), ('pedido_enviado', 'Pedido enviado'), ('pedido_entregue', 'Pedido entregue'), ('cancelado', 'Cancelado')], default='aguardando_pagamento', max_length=30),
        ),
    ]
