# Generated by Django 5.2.8 on 2025-12-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_estimativa_entrega_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('pagbank', 'PagBank'), ('stripe', 'Stripe')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_local', models.CharField(choices=[('iniciado', 'Iniciado'), ('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='iniciado', max_length=20)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload_raw', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='orders.pedido')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
